version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_app
    env_file:
      - .env

  fastapi:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi
    command: [ "/app/app.sh" ]
    ports:
      - 8000:8000
    depends_on:
      - db
    expose:
      - 8000
    restart: always
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - fastapi
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./app/conf.d:/etc/nginx/conf.d/
